name: 'mergetomain'

on:
    push:
        branches: [main]

jobs:
    build:
        name: 'Build the app'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout branch'
              uses: actions/checkout@v4
            - name: 'Install dependencies'
              run: |
                npm ci --force
            - name: 'Run built item'
              run: |
                npm run build
            - name: 'set env variable'
              run: echo "shaUsed=${{ vars.GITHUB_SHA }}" >> $GITHUB_ENV

