name: 'mergetomain'

on:
    push:
        branches: [main]

jobs:
    build:
        name: 'Build the app'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout branch'
              uses: actions/checkout@v4
            - name: 'Install dependencies'
              run: |
                npm ci --force
            - name: 'Run built item'
              run: |
                npm run build
            - name: 'write out info'
              run:
                echo "github ref=${{ github.ref }}"
                echo "github ref_name=${{ github.ref_name }}"
                echo "github event_name=${{ github.event_name }}"
                echo "github event_path=${{ github.event_path }}"
                echo "github event_push_ref=${{ github.event.push.ref }}"
                echo "github event_head_ref=${{ github.head_ref }}"

    record:
        name: 'recordinfo'
        uses: ./.github/workflows/recordinfo.yml
        with:
            passedinfo: "Passed info: github ref=${{ github.ref }} github ref_name=${{ github.ref_name }} github event_name=${{ github.event_name }} github event_path=${{ github.event_path }}"

