name: 'mergetomain'

on:
    push:
        branches: [main]

jobs:
    build:
        name: 'Build the app'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout branch'
              uses: actions/checkout@v4
            - name: 'Install dependencies'
              run: |
                npm ci --force
            - name: 'Run built item'
              run: |
                npm run build
            # - name: 'write out info'
            #   run:
            #     echo "github ref=${{ github.ref }}"
            #     echo "github ref_name=${{ github.ref_name }}"
            #     echo "github event_name=${{ github.event_name }}"
            #     echo "github event_path=${{ github.event_path }}"
            #     echo "github event_push_ref=${{ github.event.push.ref }}"
            #     echo "github head_ref=${{ github.head_ref }}"
            #     echo "github base_ref=${{ github.base_ref }}"
            - name: Get Branch Info
              id: get__branch_info
              # run: echo "::set-output name=branchInfo::$(git log -1 --pretty=reference)"
              run: echo "branchInfo=$(git log -1 --pretty=reference)" >> "$GITHUB_ENV"
                   echo ${{ github.env.branchInfo }}

    record:
        name: 'recordinfo'
        needs: [build]
        uses: ./.github/workflows/recordinfo.yml
        with:
            passedinfo: "Passed info: github ref=${{ github.ref }} github ref_name=${{ github.ref_name }} github event_name=${{ github.event_name }} github event_path=${{ github.event_path }}"
            branchInfo: ${{ github.env.branchInfo }}

