name: 'pull request'

on:
    workflow_dispatch:

jobs:
    build:
        name: 'Build the app'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout branch'
              uses: actions/checkout@v4
            - name: 'Install dependencies'
              run: |
                npm ci --force
            - name: 'Run built item'
              run: |
                npm run build
            - name: 'set env variable'
              run: echo "shaUsed=${{ vars.GITHUB_SHA }}" >> $GITHUB_ENV


    # Adding comments for testing out changes

    # check:
    #     name: 'OWASP Scan'
    #     runs-on: ubuntu-latest
    #     steps:


    # record:
    #     name: 'Record some information'
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: 

    # store:
    #     name: 'save a file'
    #     runs-on: ubuntu-latest
    #     steps:

