name: 'push request'

on:
    workflow_dispatch:

jobs:
    build:
        name: 'Build the app'
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout branch'
              uses: actions/checkout@v4
            - name: 'Install dependencies'
              run: |
                npm install
            - name: 'Run built item'
              run: |
                npm run build
            - uses: actions/github-script@v7
              env:
                report: ${{ vars.GITHUB_SHA }}
              with:
                script: |
                  console.log (env.report)


    # Adding comments for testing out changes

    # check:
    #     name: 'OWASP Scan'
    #     runs-on: ubuntu-latest
    #     steps:


    # record:
    #     name: 'Record some information'
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: 

    # store:
    #     name: 'save a file'
    #     runs-on: ubuntu-latest
    #     steps:

